run:
  timeout: 10m
linters:
  enable-all: true
  disable:
    - gomnd # deprecated (since v1.58.0) due to: The linter has been renamed. Replaced by mnd.
    - execinquery # deprecated (since v1.58.0) due to: The repository of the linter has been archived by the owner.
    - exportloopref # deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
    - wrapcheck # disable because the large amount of correspondence
    - exhaustruct # disable because unnecessary field declaration
    - rowserrcheck # disable because because of generics
    - sqlclosecheck
    - wastedassign
    # https://github.com/golangci/golangci-lint/issues/3711
    - contextcheck
    - depguard # disable because know how to use it
issues:
  exclude-rules:
    - path: main.go 
      linters:
        - funlen
