name: 'GitHub Repository Dispatch'
description: 'Create a repository dispatch event'
inputs:
  token:
    description: 'GitHub Apps Token'
    required: true
  repository:
    description: 'The repository to send the dispatch event to'
    default: ${{ github.repository }}
  event-type:
    description: 'A custom webhook event name.'
    required: true
  client-payload:
    description: 'JSON payload with extra information about the webhook event that your action or worklow may use.'
    default: '{}'
runs:
  using: 'composite'
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.1
        check-latest: true
    - name: Repository Dispatch
      run: entrypoint.sh
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        REPOSITORY: ${{ inputs.repository }}
        EVENT_TYPE: ${{ inputs.event-type }}
        CLIENT_PAYLOAD: ${{ inputs.client-payload }}
